version: '2'

services:
  websocketBrowser:
    restart: unless-stopped
    image: websocketBrowser:20210319_213600
    container_name: websocketBrowser
    ports:
      - "82:82"
    environment:
      - PORT=82
    volumes:
      - ~/websocketBrowser/:/usr/nodejs/files