version: '2'

services:
  browser:
    restart: unless-stopped
    image: browser:20210319_213600
    container_name: browser
    ports:
      - "82:82"
    environment:
      - PORT=82
    volumes:
      - ~/browser/:/usr/nodejs/files